### ISSUE TITLE
Server 2022 missing features?

### ISSUE THREAD

**Issue by pollev** [rucam/defender-comparison#1]
Hi,

I noticed that your comparison marks Server 2019/2022 as not having the following 2 features:
* Block at first sight
* Respect indicators of compromise - IPs, URLs, Domains

![image](https://user-images.githubusercontent.com/25397346/167402033-f4dc2c37-abb9-4171-9724-9342641e7337.png)

Can you confirm that this is correct? It seems strange that these features would be dropped from the previous versions of the server.

At the very least, Microsoft seems to indicate that this is supported on all platforms here: 
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-block-at-first-sight-microsoft-defender-antivirus?view=o365-worldwide

**Comment by rucam** [comment]
Thanks for raising.  This is a mistake. These features are available in 2019+. I will update in the next release.

**Comment by rucam** [comment]
August update will be released tomorrow or the day after and this is updated in it alongside a bunch of other changes :).
