### ISSUE TITLE
Restrict App Execution does not support <2019

### ISSUE THREAD

**Issue by 25004** [rucam/defender-comparison#2]
Hi, thanks so much for this guide.

I noticed one error possibly. 

App execution only supports Windows 10, version 1709 or later, Windows 11, and Windows Server 2019 or later. See Note here: https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/respond-machine-alerts?view=o365-worldwide#restrict-app-execution  The guide says it supports 2016.

Also, when I open a Server 2016 in Defender Portal I do not see the option to Restrict App Execution.

**Comment by rucam** [comment]
Thanks @25004!  This will be fixed in the next update which should be out this month.
